=== dariakrupenko/FinalTask/AdmissionWeb/WebContent/WEB-INF/commands_config/commands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.epam.by/admission"
	xmlns:adm="http://www.epam.by/admission" elementFormDefault="unqualified">

	<element name="commands-list">
		<complexType>
			<sequence>
				<element name="command" type="adm:CommandType" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	
	<complexType name="CommandType">
		<sequence>
			<element name="command-name" type="string" minOccurs="1" maxOccurs="1" />
			<element name="command-class" type="string" minOccurs="1" maxOccurs="1"/>
		</sequence>
	</complexType>
</schema>

=== dariakrupenko/FinalTask/AdmissionWeb/WebContent/WEB-INF/commands_config/commands.xml
<?xml version="1.0" encoding="UTF-8"?>

<adm:commands-list xmlns:adm="http://www.epam.by/admission" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.epam.by/admission commands.xsd">
	<command>
		<command-name>accept-settings</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.AcceptSettingsCommand
		</command-class>
	</command>
	<command>
		<command-name>add-discipline</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.discipline.AddDisciplineCommand
		</command-class>
	</command>
	<command>
		<command-name>add-faculty</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.faculty.AddFacultyCommand
		</command-class>
	</command>
	<command>
		<command-name>complete-enroll</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.enrollment.CompleteEnrollCommand
		</command-class>
	</command>
	<command>
		<command-name>cancel-registry-for-faculty</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.applicant.CancelRegistryForFacultyCommand
		</command-class>
	</command>
	<command>
		<command-name>delete-discipline</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.discipline.DeleteDisciplineCommand
		</command-class>
	</command>
	<command>
		<command-name>delete-enroll</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.enrollment.DeleteEnrollCommand
		</command-class>
	</command>
	<command>
		<command-name>delete-faculty</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.faculty.DeleteFacultyCommand
		</command-class>
	</command>
	<command>
		<command-name>enter-account</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.applicant.EnterAccountCommand
		</command-class>
	</command>
	<command>
		<command-name>get-applicant</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.applicant.GetApplicantCommand
		</command-class>
	</command>
	<command>
		<command-name>get-applicants-list</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.applicant.GetApplicantsListCommand
		</command-class>
	</command>
	<command>
		<command-name>get-discipline</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.discipline.GetDisciplineCommand
		</command-class>
	</command>
	<command>
		<command-name>get-disciplines-list</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.discipline.GetDisciplinesListCommand
		</command-class>
	</command>
	<command>
		<command-name>get-enrolls-list</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.enrollment.GetEnrollsListCommand
		</command-class>
	</command>
	<command>
		<command-name>get-faculties-list</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.GetFacultiesListCommand
		</command-class>
	</command>
	<command>
		<command-name>get-faculty</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.GetFacultyCommand
		</command-class>
	</command>
	<command>
		<command-name>get-general-statistics</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.register.GetGeneralStatisticsCommand
		</command-class>
	</command>
	<command>
		<command-name>get-register</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.register.GetRegisterCommand
		</command-class>
	</command>
	<command>
		<command-name>get-register-by-status</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.register.GetRegisterByStatusCommand
		</command-class>
	</command>
	<command>
		<command-name>login-admin</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.LoginAdminCommand
		</command-class>
	</command>
	<command>
		<command-name>login-applicant</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.applicant.LoginApplicantCommand
		</command-class>
	</command>
	<command>
		<command-name>logout</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.LogoutCommand
		</command-class>
	</command>
	<command>
		<command-name>registrate-applicant</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.applicant.RegistrateApplicantCommand
		</command-class>
	</command>
	<command>
		<command-name>registry-for-faculty</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.applicant.RegistryForFacultyCommand
		</command-class>
	</command>
	<command>
		<command-name>start-enroll</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.enrollment.StartEnrollCommand
		</command-class>
	</command>
	<command>
		<command-name>to-add-discipline-page</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.ToAddDisciplinePageCommand
		</command-class>
	</command>
	<command>
		<command-name>to-add-faculty-page</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.ToAddFacultyPageCommand
		</command-class>
	</command>
	<command>
		<command-name>to-admin-login-page</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.ToAdminLoginPageCommand
		</command-class>
	</command>
	<command>
		<command-name>to-registry-for-faculty-page</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.ToRegistryForFacultyPageCommand
		</command-class>
	</command>
	<command>
		<command-name>to-start-enroll-page</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.ToStartEnrollPageCommand
		</command-class>
	</command>
	<command>
		<command-name>to-status-page</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.ToStatusPageCommand
		</command-class>
	</command>
	<command>
		<command-name>unknown-command</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.general.UnknownCommand
		</command-class>
	</command>
	<command>
		<command-name>update-applicant</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.applicant.UpdateApplicantCommand
		</command-class>
	</command>
	<command>
		<command-name>update-discipline</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.discipline.UpdateDisciplineCommand
		</command-class>
	</command>
	<command>
		<command-name>update-faculty</command-name>
		<command-class>main.by.epam.admissionweb.command.impl.admin.faculty.UpdateFacultyCommand
		</command-class>
	</command>
</adm:commands-list>
